version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://cloudany:FQAMvoz1R2G9MKK2uLNxpIsCrbjHq4L6@dpg-d0anvjp5pdvs73bvkgk0-a.oregon-postgres.render.com/cloudany
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=https://cloudanypython-1.onrender.com
    extra_hosts:
      - "dpg-d0anvjp5pdvs73bvkgk0-a.oregon-postgres.render.com:172.17.0.1"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=https://mycloudany.onrender.com
    depends_on:
      - backend

# Удаляем сервис db, так как будем использовать базу данных на Render
# db:
#   image: postgres:14
#   ports:
#     - "5434:5432"
#   environment:
#     - POSTGRES_USER=postgres
#     - POSTGRES_PASSWORD=postgres
#     - POSTGRES_DB=cloudany
#   volumes:
#     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
