"""Add length constraints to room fields

Revision ID: 49ab6eeb51f9
Revises: 66e3e3c14c7c
Create Date: 2025-05-03 04:00:44.239974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ab6eeb51f9'
down_revision = '66e3e3c14c7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 